name: 🐛 Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
assignees:
  - mrjones2014
body:
  - type: checkboxes
    id: similar-issues
    attributes:
      label: Similar Issues
      options:
        - label: Before filing, I have searched for similar issues.
          required: true
    validations:
      required: true
  - type: textarea
    id: nvim-version
    attributes:
      label: Neovim Version
      description: "`nvim --version` output, please use a code block"
    validations:
      required: true
  - type: textarea
    id: reproduction-steps
    validations:
      required: true
    attributes:
      label: Steps to Reproduce
      value: |
        1. Open finder
        2. Select an item
        3. ...
        4. Profit?
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
    validations:
      required: true
  - type: textarea
    id: min-config
    attributes:
      label: Minimal Configuration to Reproduce
      description: "MINIMAL `init.lua` or `init.vim` to reproduce, please use a code fence with `lua` syntax specified (e.g. ```lua). All unrelated config and plugins should be removed. See [minimal init.lua template](https://github.com/mrjones2014/legendary.nvim/discussions/93)"
      value: |
        ```lua
        local root = vim.fn.fnamemodify('./.repro', ':p')

        -- set stdpaths to use .repro
        for _, name in ipairs({ 'config', 'data', 'state', 'cache' }) do
          vim.env[('XDG_%s_HOME'):format(name:upper())] = root .. '/' .. name
        end

        -- bootstrap lazy
        local lazypath = root .. '/plugins/lazy.nvim'
        if not vim.loop.fs_stat(lazypath) then
          vim.fn.system({
            'git',
            'clone',
            '--filter=blob:none',
            '--single-branch',
            'https://github.com/folke/lazy.nvim.git',
            lazypath,
          })
        end
        vim.opt.runtimepath:prepend(lazypath)

        -- install plugins
        local plugins = {
          -- do not remove the colorscheme! it makes testing nicer
          'folke/tokyonight.nvim',
          {
            'mrjones2014/legendary.nvim',
            dependencies = {
              -- place your `vim.ui.select()` handler plugin here
              -- for example:
              -- 'nvim-telescope/telescope.nvim',
              -- 'stevearc/dressing.nvim',
            },
          },
          -- add any other pugins here
        }

        require('lazy').setup(plugins, {
          root = root .. '/plugins',
        })

        require('dressing').setup()

        require('legendary').setup({
          -- add any options here
        })

        -- add anything else here
        vim.opt.termguicolors = true
        -- do not remove the colorscheme! it makes testing nicer
        vim.cmd([[colorscheme tokyonight]])
        ```
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Output from :LegendaryLog
      description: Please run `:LegendaryLog` and paste the log output between the code fences (triple back ticks) below.
      value: |
        <details>
        <summary><code>:LegendaryLog</code> output (click to expand)</summary>

        ```

        ```
        </details>
  - type: textarea
    id: details
    attributes:
      label: Additional Details and/or Screenshots
