name: ⚙️ Feature Request
description: Request a feature
title: "[Feature]: "
labels: ["enhancement"]
assignees:
  - mrjones2014
body:
  - type: checkboxes
    id: similar-issues
    attributes:
      label: Similar Issues
      options:
        - label: Before filing, I have searched for similar issues.
          required: true
    validations:
      required: true
  - type: textarea
    id: desc
    attributes:
      label: Description
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Output from `:LegendaryLog`
      description: Please paste the log output between the code fences (triple back ticks) below.
      value: |
        <details>
        <summary><code>:LegendaryLog</code> output (click to expand)</summary>

        ```

        ```
        <details>
